<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_data_2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b9f5af9d-8ab5-42a8-8a24-5434ebf6f7a3</testSuiteGuid>
   <testCaseLink>
      <guid>b97e6050-8e3b-45c0-8921-c259e7ea3590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Web_16</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ca0c783c-7240-4939-811d-89583a09e630</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ca0c783c-7240-4939-811d-89583a09e630</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8c580e3b-690e-46c5-af27-f2b8c95016fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca0c783c-7240-4939-811d-89583a09e630</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1fe0e66f-bd00-4b3b-b27e-f12d0d4e8577</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
