<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Data_3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>969f8640-5f55-445f-96a4-fc05f88fa06a</testSuiteGuid>
   <testCaseLink>
      <guid>381d70fb-3062-4c1a-950c-9232c37e4da5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Web_17_data</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>494ed2a6-0acf-40a5-b20f-6d6b99f9badb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData3</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>494ed2a6-0acf-40a5-b20f-6d6b99f9badb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>4f311804-4979-4072-8ba6-600046a18b79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>494ed2a6-0acf-40a5-b20f-6d6b99f9badb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5ec892dd-9bd4-4d82-b996-57a1e8d56210</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
