<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Search query__yb_1kafsg5</name>
   <tag></tag>
   <elementGuidId>f2456ba7-e0ca-4472-8eb4-4f1c79569251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Search query'])[1]/following::*[name()='svg'][5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg._yb_1kafsg5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;rocket_GA_desk_test-3-v1\,TNAPI001\,ushnelsf_usersyncbb_ctrl-copy\,TNBE006&quot;] >> internal:label=&quot;Search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>bf9d2f27-62b7-4e31-bbef-f0e84ab8fd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>f083c7f1-7bdb-4691-891e-8687a8be1c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>734a67b0-c524-4348-a44e-d30e290b5b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>065993b4-6764-463e-9134-ea1c05fefbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>59625af3-280e-44e2-b0c5-837dfb3fcf99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ef6411a9-05bb-49c1-b956-01bf2a0842f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_1kafsg5</value>
      <webElementGuid>9c69d08a-e71b-492c-acb7-50a469d9780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-search&quot;)/svg[@class=&quot;_yb_1kafsg5&quot;]</value>
      <webElementGuid>72f4d376-1601-4761-a6ff-07568a0a8f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search query'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>b1883823-6268-4d46-bb0e-d9c1018697d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select edition'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>6e549977-7aa8-4f04-95f2-708de67d838d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
