<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notes</name>
   <tag></tag>
   <elementGuidId>f420f8ea-46d1-4659-9020-74b4640b7964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Notes')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.widget.block.block-static-block > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dcb18ede-6a6a-4095-ad7e-0ff5ea613610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://softwaretestingboard.com/magento-store-notes/?utm_source=magento_store&amp;utm_medium=banner&amp;utm_campaign=notes_promo&amp;utm_id=notes_promotion</value>
      <webElementGuid>c9f71a38-7d64-4621-b2ba-c3c0f8acae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c6d8fc68-901f-478c-af25-92b8b78fad5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>2f356622-acf4-47fb-957c-426b476e45bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notes </value>
      <webElementGuid>7cdbb262-a075-475d-94b0-80bfa596dc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cms-home cms-index-index page-layout-1column&quot;]/div[@class=&quot;page-wrapper&quot;]/footer[@class=&quot;page-footer&quot;]/div[@class=&quot;footer content&quot;]/div[@class=&quot;links&quot;]/div[@class=&quot;widget block block-static-block&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>5f03c03c-70e2-4d15-b113-d852ad5e8218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Notes')]</value>
      <webElementGuid>fcd6b088-c6d4-457f-aff4-305e3d8e813f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[6]/following::a[1]</value>
      <webElementGuid>6b18e9fa-0417-4753-a126-644d53ba8460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Wish List'])[6]/following::a[2]</value>
      <webElementGuid>72207752-62b8-4bdc-95ff-f057fee6f8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice API Testing using Magento 2'])[1]/preceding::a[1]</value>
      <webElementGuid>9620200a-1bff-4da5-80c9-eb73f918693d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write for us'])[1]/preceding::a[2]</value>
      <webElementGuid>44ff3248-948d-47ac-9e66-58cd71bd209e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://softwaretestingboard.com/magento-store-notes/?utm_source=magento_store&amp;utm_medium=banner&amp;utm_campaign=notes_promo&amp;utm_id=notes_promotion')]</value>
      <webElementGuid>b8b7de0c-e8bf-496b-8ebd-e601cd92aefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/ul/li/a</value>
      <webElementGuid>ae0a25a4-037b-43ce-9d94-8d1cccd28c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://softwaretestingboard.com/magento-store-notes/?utm_source=magento_store&amp;utm_medium=banner&amp;utm_campaign=notes_promo&amp;utm_id=notes_promotion' and (text() = 'Notes ' or . = 'Notes ')]</value>
      <webElementGuid>1b9ff441-3404-473f-871a-320c8e247b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
