<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Store</name>
   <tag></tag>
   <elementGuidId>07e0011d-efc9-4716-aaab-0918e5223447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='globalnav-list']/li[2]/div/div/div/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.globalnav-link-text-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Store&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29984bda-7500-412c-973c-a71922b5b1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>globalnav-link-text-container</value>
      <webElementGuid>b757762e-8d77-4fb1-ad9c-e59513fbc605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Store</value>
      <webElementGuid>c5295104-0d62-4b99-b942-fe5b519f041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalnav-list&quot;)/li[@class=&quot;globalnav-item globalnav-menu&quot;]/div[@class=&quot;globalnav-flyout&quot;]/div[@class=&quot;globalnav-menu-list&quot;]/div[@class=&quot;globalnav-item globalnav-item-store globalnav-item-menu globalnav-item-submenu globalnav-item-flyout-open&quot;]/ul[@class=&quot;globalnav-submenu-trigger-group&quot;]/li[@class=&quot;globalnav-submenu-trigger-item&quot;]/a[@class=&quot;globalnav-link globalnav-submenu-trigger-link globalnav-link-store&quot;]/span[@class=&quot;globalnav-link-text-container&quot;]</value>
      <webElementGuid>d3451ae1-3314-4a3b-a631-f1e9c657b896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='globalnav-list']/li[2]/div/div/div/ul/li/a/span</value>
      <webElementGuid>601502ee-f3ca-4aca-8725-03b030e543c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple'])[3]/following::span[1]</value>
      <webElementGuid>997cf44e-1b94-4da8-8f53-8c8426f9d795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple'])[2]/following::span[5]</value>
      <webElementGuid>6f72804d-cfc2-45f1-b818-e96f65e45e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/preceding::span[6]</value>
      <webElementGuid>c9f95999-a838-4783-bfe7-2b68b80f2289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li/a/span</value>
      <webElementGuid>e432b8d9-a4a6-443b-8699-9f421cb710af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Store' or . = 'Store')]</value>
      <webElementGuid>b82c1bc3-d511-431b-8e8c-c993c9ebc2b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
