<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agile Testing</name>
   <tag></tag>
   <elementGuidId>6d42b755-2df7-4d68-a644-ddff915172d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4569']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4569 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Agile Testing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f06601f9-baf6-473f-b77e-caff42c106f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.guru99.com/agile-testing-course.html</value>
      <webElementGuid>528fb139-8e44-44aa-932e-0febe7cbaebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agile Testing</value>
      <webElementGuid>8b1daeff-ee9a-4e5d-b4a6-b06cb8c39637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4569&quot;)/a[1]</value>
      <webElementGuid>7fc185f8-0c41-4d9e-80b0-2e90f8b4613b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4569']/a</value>
      <webElementGuid>b433c19e-e7a1-401b-80f4-b9398bef5e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agile Testing')]</value>
      <webElementGuid>4763d925-54b6-43ba-9835-674e5b2a2a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>dfab1d8c-7707-42ab-b32d-27bb8a6d6346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JUnit'])[1]/preceding::a[1]</value>
      <webElementGuid>9d7176ae-4d4c-4caa-ac86-cd5a08aa8c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Center(ALM)'])[1]/preceding::a[2]</value>
      <webElementGuid>d8f292bd-75eb-41ee-941f-68e047b9ec97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agile Testing']/parent::*</value>
      <webElementGuid>4bbcb25a-a1e7-4c2e-9411-6b82d66f62e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.guru99.com/agile-testing-course.html')]</value>
      <webElementGuid>3fcffc39-99af-436f-84f1-0d43dbdcd7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>c1d4113c-e6ef-4541-8a1f-9e576934c28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.guru99.com/agile-testing-course.html' and (text() = 'Agile Testing' or . = 'Agile Testing')]</value>
      <webElementGuid>21974bb1-c1a2-457b-b196-94e728d32373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
