<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HP Loadrunner</name>
   <tag></tag>
   <elementGuidId>5e8117e0-2e0f-45a4-b54b-5bfdd1e68743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4584']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4584 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;HP Loadrunner&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76852172-ff86-40e9-84b7-4afebaaf4401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/loadrunner-v12-tutorials.html</value>
      <webElementGuid>1208ce0b-712b-43a6-9528-8b0c0142efe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trid</name>
      <type>Main</type>
      <value>147</value>
      <webElementGuid>1c931945-fde8-4ad8-967b-42a77e3bdb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HP Loadrunner</value>
      <webElementGuid>daa5c573-3acd-4dd7-8eea-7db9ac844fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4584&quot;)/a[1]</value>
      <webElementGuid>49e0ec56-46bb-4ca2-9d53-cae2f679d541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4584']/a</value>
      <webElementGuid>954179e9-27b5-4f8b-9bc1-e886ac48e804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HP Loadrunner')]</value>
      <webElementGuid>9b878e85-9bf4-42f8-9b0f-6fa0de391e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bugzilla'])[1]/following::a[1]</value>
      <webElementGuid>b37c332f-07e0-44bc-a5a7-90e0ebf3486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Center(ALM)'])[1]/following::a[2]</value>
      <webElementGuid>13e9d76f-7317-4d1e-aa46-ed690bc25518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPA'])[1]/preceding::a[1]</value>
      <webElementGuid>9b360aa0-c540-4e59-8482-6261a304aec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cucumber'])[1]/preceding::a[2]</value>
      <webElementGuid>058120ae-352d-45bf-aade-dfdfc4519908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HP Loadrunner']/parent::*</value>
      <webElementGuid>419beaf4-ac88-44b3-b2ca-c2aff8748738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/loadrunner-v12-tutorials.html')]</value>
      <webElementGuid>ac1d24d1-c5c1-4a59-b787-c89c77c308b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a</value>
      <webElementGuid>e8bc8713-3859-48bd-9afb-2349a8106648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/loadrunner-v12-tutorials.html' and (text() = 'HP Loadrunner' or . = 'HP Loadrunner')]</value>
      <webElementGuid>53004483-05a0-4027-8e4d-c52da0ca97cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
